### ISSUE TITLE
User kann sich anmelden

### ISSUE THREAD

**Issue by RobRobRoberto** [RobRobRoberto/Capstone_Buecherclub#8]
### Value Statement
As a user i 
I want a page where i can sign in
so that my data is save
### Description
The welcome page has a heading saying "Willkommen" and a button which leads to the sign in page.
On the sign in page the user will use a har codes username and password to get his access.
After his login he will see an empty feed page.
### Acceptance Criteria
- [ ] feed content is scrollable
- [ ] the welcome page be minimalist and stylish

### Tasks
- [ ] create the necessary directories
- [ ] create the welcome page
- [ ] create the sign in page
- [ ] create an empty feed
- [ ] connect all pages via react router
- [ ] integrate database with a hard coded username and password
- [ ] create protected route
